services:
  - type: web
    name: doggzi-office-os
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn office_os.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "true"
      - key: JWT_ACCESS_MINUTES
        value: "60"
      - key: JWT_REFRESH_DAYS
        value: "7"
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: "doggzi_office_os"
      - key: DJANGO_SECRET_KEY
        generateValue: true
